name: Deploy
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Zola
      uses: taiki-e/install-action@v2
      with:
        tool: zola@0.16.1
    - name: Zola Build
      run: |
        zola build
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        if_key_exists: fail
    - name: rsync over SSH
      run: |
        rsync -av public/ gh-deploy@acmesf.com:
